package com.example.enews.bean.sport

import com.example.enews.bean.sport.Imgextra

data class T1348649079062 (var sourceId: String,
                      var imgextra: List<Imgextra>,
                      var template: String,
                      var riskLevel : Int,
                      var upTimes : Int,
                      var lmodify: String,
                      var source: String,
                      var postid: String,
                      var title: String,
                      var mtime: String,
                      var hasImg : Int,
                      var topicid: String,
                      var topic_background: String,
                      var digest: String,
                      var boardid: String,
                      var alias: String,
                      var hasAD : Int,
                      var imgsrc: String,
                      var ptime: String,
                      var daynum: String,
                      var extraShowFields: String,
                      var hasHead : Int,
                      var order : Int,
                      var votecount : Int,
                      var hasCover : Boolean,
                      var docid: String,
                      var tname: String,
                      var url_3w: String,
                      var priority : Int,
                      var downTimes : Int,
                      var url: String,
                      var quality : Int,
                      var commentStatus : Int,
                      var ename: String,
                      var replyCount : Int,
                      var ltitle: String,
                      var hasIcon : Boolean,
                      var subtitle: String,
                      var cid: String)