package com.example.enews.bean.video

data class VideoList (
    var sizeHD :Int,
    var upTimes :Int,
    var mp4Hd_url: String,
    var description: String,
    var title: String,
    var mp4_url: String,
    var vid: String,
    var cover: String,
    var sizeSHD :Int,
    var playersize :Int,
    var ptime: String,
    var m3u8_url: String,
    var topicImg: String,
    var votecount :Int,
    var length: Int,
    var videosource: String,
    var downTimes :Int,
    var m3u8Hd_url: String,
    var sizeSD :Int,
    var topicSid: String,
    var commentStatus :Int,
    var playCount :Int,
    var replyCount :Int,
    var replyBoard: String,
    var replyid: String,
    var topicName: String,
    var sectiontitle: String,
    var topicDesc: String)